# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
target 'PublishMoments-demo' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for PublishMoments-demo
    pod 'SDWebImage', '~> 3.8.1'
    pod 'LaunchAnimation', '~> 0.1.0'
    
    target 'PublishMoments-demoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'PublishMoments-demoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
