# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
target 'PublishMoments-demo' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    # Pods for PublishMoments-demo
    # 在这里配置项目要用到的第三方依赖库
    
    target 'PublishMoments-demoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'PublishMoments-demoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
